name: Sync Faster-Upstream Branch

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - faster
  push:
    branches:
      - faster
  workflow_dispatch:

jobs:
  sync-faster-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/lobehub/lobe-chat.git
          git fetch upstream main

      - name: Update faster-upstream branch
        run: |
          git checkout -B faster-upstream origin/faster
          git rebase upstream/main
          git push origin faster-upstream --force
